baseURL = 'https://xlikai.github.io/'
languageCode = 'zh-cn'
title = 'xlikai çš„æŠ€æœ¯æ¢ç´¢åšå®¢'
theme = 'PaperMod'

[params]
  env = 'production'
  title = 'åœ¨VSATçš„MY'
  description = 'è®°å½•VSATçš„MYçš„æˆé•¿å†ç¨‹'
  author = 'xlikai'
    [params.homeInfoParams]
        Title = "ä½ å¥½ï¼Œæ¬¢è¿æ¥åˆ°æˆ‘çš„åšå®¢ ğŸ‘‹"
        Content = "è¿™é‡Œä¸»è¦è®°å½•æˆ‘å¯¹ç®—æ³•çš„ç ”ç©¶ã€Linuxä½¿ç”¨å¿ƒå¾—ã€‚"
    [params.labels]
        text = "Xlikai Home"
