baseURL = 'https://xlikai.github.io/'
languageCode = 'zh-cn'
title = 'xlikaiçš„åšå®¢'
theme = 'PaperMod'

[params]
    env               = 'production'
    defaultTheme      = 'auto'
    disableThemeToggle= false  # å¦‚æœè®¾ä¸º trueï¼Œè¯»è€…å°±ä¸èƒ½è‡ªå·±åˆ‡æ¢æ·±è‰²/æµ…è‰²æ¨¡å¼äº†ï¼Œå»ºè®®è®¾ä¸º false
    author            = 'xlikai'
    authorAvatar      = "img/avatar.jpg" # è¯·å°†å›¾ç‰‡æ”¾å…¥ static/img/avatar.png
    description       = 'è®°å½•VSATçš„æˆé•¿å†ç¨‹'
    
    # å¼€å¯ä»£ç é«˜äº®å’Œæœç´¢
    ShowCodeCopyButtons = true # æ—¢ç„¶æ˜¯æ·±åº¦å­¦ä¹ åšå®¢ï¼Œå»ºè®®å¼€å¯ä»£ç ä¸€é”®å¤åˆ¶

    [params.homeInfoParams]
        Title = "ä½ å¥½ï¼Œæ¬¢è¿æ¥åˆ°xlikaiçš„åšå®¢ ğŸ‘‹"
        Content = "è¿™é‡Œä¸»è¦è®°å½•æˆ‘å¯¹ç®—æ³•çš„ç ”ç©¶ã€Linuxä½¿ç”¨å¿ƒå¾—å’Œæ—¥å¸¸çš„å­¦ä¹ ã€‚"
    
    [params.label]
        text = "Xlikai Home"

    # æœç´¢å‚æ•°
    [params.fuseOpts]
        isCaseSensitive = false
        shouldSort = true
        location = 0
        distance = 1000
        threshold = 0.4
        minMatchCharLength = 0
        keys = ["title", "permalink", "summary", "content"]
    
    [params.assets]
        disableHLJS = false
        favicon = "favicon.jpg"
 
[[params.socialIcons]]
    name = "github"
    url = "https://github.com/xlikai"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[[menu.main]]
    name = "å­¦ä¹ ç¬”è®°"
    url = "posts"
    weight = 20

[[menu.main]]
    name = "é¡¹ç›®è®°å½•"
    url = "link"
    weight = 30

[[menu.main]]
    name = "æ¯æœˆè®°å½•"
    url = "monthly"
    weight = 40

[[menu.main]]
    name = " å…³äº "
    url = "about"
    weight = 50