baseURL = 'https://xlikai.github.io/'
languageCode = 'zh-cn'
title = 'xlikaiçš„åšå®¢'
theme = 'PaperMod'

[params]
    env               = 'production'
    defaultTheme      = 'auto'
    disableThemeToggle = false  # å¦‚æœè®¾ä¸º trueï¼Œè¯»è€…å°±ä¸èƒ½è‡ªå·±åˆ‡æ¢æ·±è‰²/æµ…è‰²æ¨¡å¼äº†ï¼Œå»ºè®®è®¾ä¸º false
    author            = 'xlikai'
    description       = 'è®°å½•VSATçš„æˆé•¿å†ç¨‹'
    
    assets = { disableHLJS = false } # ç¡®ä¿èµ„æºåŠ è½½å¼€å¯
    # å‘Šè¯‰ä¸»é¢˜åŠ è½½è‡ªå®šä¹‰ css
    customCSS = ["css/extended.css"]

    [params.homeInfoParams]
        Title = "ä½ å¥½ï¼Œæ¬¢è¿æ¥åˆ°xlikaiçš„åšå®¢ ğŸ‘‹"
        Content = "è¿™é‡Œä¸»è¦è®°å½•æˆ‘å¯¹ç®—æ³•çš„ç ”ç©¶ã€Linuxä½¿ç”¨å¿ƒå¾—å’Œæ—¥å¸¸çš„å­¦ä¹ ã€‚"
    
    [params.label]
        text = "Xlikai Home"    # ç½‘é¡µå·¦ä¸Šè§’æ˜¾ç¤ºçš„åç§°

    [params.fuseOpts]
        isCaseSensitive = false
        shouldSort = true
        location = 0
        distance = 1000
        threshold = 0.4
        minMatchCharLength = 0
        keys = ["title", "permalink", "summary", "content"]

[outputs]
    home = ["HTML", "RSS", "JSON"]

[[menu.main]]
    name = "ğŸ” æœç´¢"
    url = "search" # è¿™é‡Œå¯¹åº”çš„æ˜¯ content/search.md
    weight = 10

[[menu.main]]
    name = "ğŸ“š æ–‡ç« "
    url = "posts"
    weight = 20


